### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [GA114/tc359p7#1]
When I submit a blank form, I'm getting an `Internal Server Error`. Can you fix this?

**Comment by GA114** [comment]
I knew I shouldn't have made the date fields' type `text`.

**Comment by chrisvfritz** [comment]
It looks like you've made some good updates to your code. Can you push up to Heroku also?

**Comment by GA114** [comment]
Aw geez, I'm remembering everything piecemeal. Done.

**Comment by chrisvfritz** [comment]
:+1: Much better!
